### ISSUE TITLE
maggtuoriol

### ISSUE THREAD

**Issue by chattmaggiemae10** [JeroenMols/ReactTicTacToe#2]
My bloggin

**Comment by chattmaggiemae10** [comment]
Maggie Mae  assignment
- maggtuoriol 
Blogging 
Information 
Recovery 
Life 
Relationships
Relapses 
Entertainment 
Not escape reality 9 zero
Making a trigger seem small ****
Emotions 
Stay out of my head
Scary trickster,lengthy story telling 
Passifieng

**Comment by chattmaggiemae10** [comment]
****beware of little slips ****
****never minimize what using can cause, cost,health ****check out vitamin supplements for healthy skin and liver disease prevention ****
****Avoid diseases I don't have ****
__brain gummmys__adhd__focus__
Fish oil capsules __research liver toxicity __bioten__vitamen A, B, C, D, E__pottasuom__cbd gummys__heart health__nauseated,sour stomach __
Headache __exercise__walk__jog__
Run__mental health __first thing in morning drink water, read a Psalm, read Proverb, read one chapter of bible
Pray, praise, walk in place, drink water⁰

**Comment by JeroenMols** [comment]
spam
